### ISSUE TITLE
Initial Creation of the XTS tool

### ISSUE THREAD

**Issue by TB-1993** [rdkcentral/xts_core#1]
## Goal: Create the initial version of the core XTS tool
The core XTS will simply be for parsing .xts files and using the information within them to run, build and list tests.

## Acceptance Criteria
The xts tool must:
- Detect and parse .xts yaml file from the current directory.
- Run commands listed in the yaml files
- Provide run, build and list methods
- Have adequate documentation for a new users to install and use it

**Comment by TB-1993** [comment]
Documenting this has taken longer than expected, with the addition of me going on holiday in-between. Hunch the end date moving.

**Comment by Ulrond** [comment]
* Delivery to be simple with expansion possibilities for the future.
